from scancodes import *

keyCombos = [
    [scancode.BacktickTilde],
    [scancode.OneExclam],
    [scancode.TwoAt],
    [scancode.ThreePound],
    [scancode.FourDollar],
    [scancode.FivePercent],
    [scancode.SixCaret],
    [scancode.SevenAmpersand],
    [scancode.EightAsterisk],
    [scancode.NineLeftParen],
    [scancode.ZeroRightParen],
    [scancode.MinusUnderscore],
    [scancode.EqualPlus],

    [scancode.LShift, scancode.BacktickTilde],
    [scancode.LShift, scancode.OneExclam],
    [scancode.LShift, scancode.TwoAt],
    [scancode.LShift, scancode.ThreePound],
    [scancode.LShift, scancode.FourDollar],
    [scancode.LShift, scancode.FivePercent],
    [scancode.LShift, scancode.SixCaret],
    [scancode.LShift, scancode.SevenAmpersand],
    [scancode.LShift, scancode.EightAsterisk],
    [scancode.LShift, scancode.NineLeftParen],
    [scancode.LShift, scancode.ZeroRightParen],
    [scancode.LShift, scancode.MinusUnderscore],
    [scancode.LShift, scancode.EqualPlus],

    [scancode.Backspace],
    [scancode.Tab],

    [scancode.Q],
    [scancode.W],
    [scancode.E],
    [scancode.R],
    [scancode.T],
    [scancode.Y],
    [scancode.U],
    [scancode.I],
    [scancode.O],
    [scancode.P],
    [scancode.LeftSquareBracket],
    [scancode.RightSquareBracket],
    [scancode.BackslashPipe],

    [scancode.LShift, scancode.Q],
    [scancode.LShift, scancode.W],
    [scancode.LShift, scancode.E],
    [scancode.LShift, scancode.R],
    [scancode.LShift, scancode.T],
    [scancode.LShift, scancode.Y],
    [scancode.LShift, scancode.U],
    [scancode.LShift, scancode.I],
    [scancode.LShift, scancode.O],
    [scancode.LShift, scancode.P],
    [scancode.LShift, scancode.LeftSquareBracket],
    [scancode.LShift, scancode.RightSquareBracket],
    [scancode.LShift, scancode.BackslashPipe],

    # [scancode.CapsLock],

    [scancode.A],
    [scancode.S],
    [scancode.D],
    [scancode.F],
    [scancode.G],
    [scancode.H],
    [scancode.J],
    [scancode.K],
    [scancode.L],
    [scancode.SemicolonColon],
    [scancode.SingleDoubleQuote],

    [scancode.LShift, scancode.A],
    [scancode.LShift, scancode.S],
    [scancode.LShift, scancode.D],
    [scancode.LShift, scancode.F],
    [scancode.LShift, scancode.G],
    [scancode.LShift, scancode.H],
    [scancode.LShift, scancode.J],
    [scancode.LShift, scancode.K],
    [scancode.LShift, scancode.L],
    [scancode.LShift, scancode.SemicolonColon],
    [scancode.LShift, scancode.SingleDoubleQuote],

    # [scancode.nonUS1],
    [scancode.Enter],
    [scancode.LShift],

    [scancode.Z],
    [scancode.X],
    [scancode.C],
    [scancode.V],
    [scancode.B],
    [scancode.N],
    [scancode.M],
    [scancode.CommaLeftAngle],
    [scancode.PeriodRightAngle],
    [scancode.SlashQuestion],

    [scancode.LShift, scancode.Z],
    [scancode.LShift, scancode.X],
    [scancode.LShift, scancode.C],
    [scancode.LShift, scancode.V],
    [scancode.LShift, scancode.B],
    [scancode.LShift, scancode.N],
    [scancode.LShift, scancode.M],
    [scancode.LShift, scancode.CommaLeftAngle],
    [scancode.LShift, scancode.PeriodRightAngle],
    [scancode.LShift, scancode.SlashQuestion],

    # [scancode.RShift],
    [scancode.LCtrl],
    [scancode.LAlt],
    [scancode.Space],
    # [scancode.RAlt],
    # [scancode.RCtrl],
    # [scancode.Insert],
    [scancode.Delete],
    [scancode.Home],
    [scancode.End],
    [scancode.PgUp],
    [scancode.PgDn],
    [scancode.Left],
    [scancode.Up],
    [scancode.Down],
    [scancode.Right],
    # [scancode.NumLock],
    # [scancode.KP7Home],
    # [scancode.KP4Left],
    # [scancode.KP1End],
    # [scancode.KPSlash],
    # [scancode.KP8Up],
    # [scancode.KP5],
    # [scancode.KP2Down],
    # [scancode.KP0Ins],
    # [scancode.KPAsterisk],
    # [scancode.KP9PgUp],
    # [scancode.KP6Right],
    # [scancode.KP3PgDn],
    # [scancode.KPPeriodDel],
    # [scancode.KPMinus],
    # [scancode.KPPlus],
    # [scancode.KPEnter],
    [scancode.Esc],
    [scancode.F1],
    [scancode.F2],
    [scancode.F3],
    [scancode.F4],
    [scancode.F5],
    [scancode.F6],
    [scancode.F7],
    [scancode.F8],
    [scancode.F9],
    [scancode.F10],
    [scancode.F11],
    [scancode.F12],
    # [scancode.PrtScr],
    # [scancode.AltSysRq],
    # [scancode.ScrollLock],
    # [scancode.CtrlBreak],
    # [scancode.LWin],
    # [scancode.RWin],
    # [scancode.Menu],
    # [scancode.Sleep],
    # [scancode.Power],
    # [scancode.Wake],
]