from scancodes import scancode
from keycodes import keycode


keynames = {
    scancode.BacktickTilde: "`",
    scancode.OneExclam: "1",
    scancode.TwoAt: "2",
    scancode.ThreePound: "3",
    scancode.FourDollar: "4",
    scancode.FivePercent: "5",
    scancode.SixCaret: "6",
    scancode.SevenAmpersand: "7",
    scancode.EightAsterisk: "8",
    scancode.NineLeftParen: "9",
    scancode.ZeroRightParen: "0",
    scancode.MinusUnderscore: "-",
    scancode.EqualPlus: "=",

    (scancode.LShift, scancode.BacktickTilde): "~",
    (scancode.LShift, scancode.OneExclam): "!",
    (scancode.LShift, scancode.TwoAt): "@",
    (scancode.LShift, scancode.ThreePound): "#",
    (scancode.LShift, scancode.FourDollar): "$",
    (scancode.LShift, scancode.FivePercent): "%",
    (scancode.LShift, scancode.SixCaret): "^",
    (scancode.LShift, scancode.SevenAmpersand): "&",
    (scancode.LShift, scancode.EightAsterisk): "*",
    (scancode.LShift, scancode.NineLeftParen): "(",
    (scancode.LShift, scancode.ZeroRightParen): ")",
    (scancode.LShift, scancode.MinusUnderscore): "_",
    (scancode.LShift, scancode.EqualPlus): "+",

    scancode.Backspace: "Backspace",
    scancode.Tab: "Tab",

    scancode.Q: "q",
    scancode.W: "w",
    scancode.E: "e",
    scancode.R: "r",
    scancode.T: "t",
    scancode.Y: "y",
    scancode.U: "u",
    scancode.I: "i",
    scancode.O: "o",
    scancode.P: "p",
    scancode.LeftSquareBracket: "[",
    scancode.RightSquareBracket: "]",
    scancode.BackslashPipe: "\\",

    (scancode.LShift, scancode.Q): "Q",
    (scancode.LShift, scancode.W): "W",
    (scancode.LShift, scancode.E): "E",
    (scancode.LShift, scancode.R): "R",
    (scancode.LShift, scancode.T): "T",
    (scancode.LShift, scancode.Y): "Y",
    (scancode.LShift, scancode.U): "U",
    (scancode.LShift, scancode.I): "I",
    (scancode.LShift, scancode.O): "O",
    (scancode.LShift, scancode.P): "P",
    (scancode.LShift, scancode.LeftSquareBracket): "{",
    (scancode.LShift, scancode.RightSquareBracket): "}",
    (scancode.LShift, scancode.BackslashPipe): "|",

    scancode.CapsLock: "CapsLock",

    scancode.A: "a",
    scancode.S: "s",
    scancode.D: "d",
    scancode.F: "f",
    scancode.G: "g",
    scancode.H: "h",
    scancode.J: "j",
    scancode.K: "k",
    scancode.L: "l",
    scancode.SemicolonColon: ";",
    scancode.SingleDoubleQuote: "'",

    (scancode.LShift, scancode.A): "A",
    (scancode.LShift, scancode.S): "S",
    (scancode.LShift, scancode.D): "D",
    (scancode.LShift, scancode.F): "F",
    (scancode.LShift, scancode.G): "G",
    (scancode.LShift, scancode.H): "H",
    (scancode.LShift, scancode.J): "J",
    (scancode.LShift, scancode.K): "K",
    (scancode.LShift, scancode.L): "L",
    (scancode.LShift, scancode.SemicolonColon): ":",
    (scancode.LShift, scancode.SingleDoubleQuote): "\"",

    scancode.nonUS1: "non-US-1",
    scancode.Enter: "Enter",
    scancode.LShift: "Shift",

    scancode.Z: "z",
    scancode.X: "x",
    scancode.C: "c",
    scancode.V: "v",
    scancode.B: "b",
    scancode.N: "n",
    scancode.M: "m",
    scancode.CommaLeftAngle: ",",
    scancode.PeriodRightAngle: ".",
    scancode.SlashQuestion: "/",

    (scancode.LShift, scancode.Z): "Z",
    (scancode.LShift, scancode.X): "X",
    (scancode.LShift, scancode.C): "C",
    (scancode.LShift, scancode.V): "V",
    (scancode.LShift, scancode.B): "B",
    (scancode.LShift, scancode.N): "N",
    (scancode.LShift, scancode.M): "M",
    (scancode.LShift, scancode.CommaLeftAngle): "<",
    (scancode.LShift, scancode.PeriodRightAngle): ">",
    (scancode.LShift, scancode.SlashQuestion): "?",

    scancode.RShift: "RShift",
    scancode.LCtrl: "Ctrl",
    scancode.LAlt: "Alt",
    scancode.Space: "Space",
    scancode.RAlt: "RAlt",
    scancode.RCtrl: "RCtrl",
    scancode.Insert: "Insert",
    scancode.Delete: "Delete",
    scancode.Home: "Home",
    scancode.End: "End",
    scancode.PgUp: "PgUp",
    scancode.PgDn: "PgDn",
    scancode.Left: "Left",
    scancode.Up: "Up",
    scancode.Down: "Down",
    scancode.Right: "Right",
    scancode.NumLock: "NumLock",
    scancode.KP7Home: "KP-7 / Home",
    scancode.KP4Left: "KP-4 / Left",
    scancode.KP1End: "KP-1 / End",
    scancode.KPSlash: "KP-/",
    scancode.KP8Up: "KP-8 / Up",
    scancode.KP5: "KP-5",
    scancode.KP2Down: "KP-2 / Down",
    scancode.KP0Ins: "KP-0 / Ins",
    scancode.KPAsterisk: "KP-*",
    scancode.KP9PgUp: "KP-9 / PgUp",
    scancode.KP6Right: "KP-6 / Right",
    scancode.KP3PgDn: "KP-3 / PgDn",
    scancode.KPPeriodDel: "KP-. / Del",
    scancode.KPMinus: "KP--",
    scancode.KPPlus: "KP-+",
    scancode.KPEnter: "KP-Enter",
    scancode.Esc: "Esc",
    scancode.F1: "F1",
    scancode.F2: "F2",
    scancode.F3: "F3",
    scancode.F4: "F4",
    scancode.F5: "F5",
    scancode.F6: "F6",
    scancode.F7: "F7",
    scancode.F8: "F8",
    scancode.F9: "F9",
    scancode.F10: "F10",
    scancode.F11: "F11",
    scancode.F12: "F12",
    scancode.PrtScr: "PrtScr",
    scancode.AltSysRq: "AltSysRq",
    scancode.ScrollLock: "ScrollLock",
    scancode.CtrlBreak: "CtrlBreak",
    scancode.LWin: "Win",
    scancode.RWin: "RWin",
    scancode.Menu: "Menu",
    scancode.Sleep: "Sleep",
    scancode.Power: "Power",
    scancode.Wake: "Wake",

    scancode.Mute: "Mute",
    scancode.VolUp: "VolumeUp",
    scancode.VolDown: "VolumeDown",
    scancode.NextTrack: "NextTrack",
    scancode.PrevTrack: "PrevTrack",
    scancode.Stop: "Stop",
    scancode.PlayPause: "PlayPause",
    scancode.BrightUp: "BrightnessUp",
    scancode.BrightDown: "BrightnessDown",



    keycode.KC_NO: "KC_NO",
    keycode.KC_TRANSPARENT: "KC_TRANSPARENT",
    keycode.KC_A: "a",
    keycode.KC_B: "b",
    keycode.KC_C: "c",
    keycode.KC_D: "d",
    keycode.KC_E: "e",
    keycode.KC_F: "f",
    keycode.KC_G: "g",
    keycode.KC_H: "h",
    keycode.KC_I: "i",
    keycode.KC_J: "j",
    keycode.KC_K: "k",
    keycode.KC_L: "l",
    keycode.KC_M: "m",
    keycode.KC_N: "n",
    keycode.KC_O: "o",
    keycode.KC_P: "p",
    keycode.KC_Q: "q",
    keycode.KC_R: "r",
    keycode.KC_S: "s",
    keycode.KC_T: "t",
    keycode.KC_U: "u",
    keycode.KC_V: "v",
    keycode.KC_W: "w",
    keycode.KC_X: "x",
    keycode.KC_Y: "y",
    keycode.KC_Z: "z",
    keycode.KC_1: "1",
    keycode.KC_2: "2",
    keycode.KC_3: "3",
    keycode.KC_4: "4",
    keycode.KC_5: "5",
    keycode.KC_6: "6",
    keycode.KC_7: "7",
    keycode.KC_8: "8",
    keycode.KC_9: "9",
    keycode.KC_0: "0",
    keycode.KC_ENTER: "Enter",
    keycode.KC_ESCAPE: "Escape",
    keycode.KC_BACKSPACE: "Backspace",
    keycode.KC_TAB: "Tab",
    keycode.KC_SPACE: "Space",
    keycode.KC_MINUS: "-",
    keycode.KC_EQUAL: "=",
    keycode.KC_LEFT_BRACKET: "[",
    keycode.KC_RIGHT_BRACKET: "]",
    keycode.KC_BACKSLASH: "\\",
    keycode.KC_NONUS_HASH: "KC_NONUS_HASH",
    keycode.KC_SEMICOLON: ";",
    keycode.KC_QUOTE: "'",
    keycode.KC_GRAVE: "`",
    keycode.KC_COMMA: ",",
    keycode.KC_DOT: ".",
    keycode.KC_SLASH: "/",
    keycode.KC_CAPS_LOCK: "CapsLock",
    keycode.KC_F1: "F1",
    keycode.KC_F2: "F2",
    keycode.KC_F3: "F3",
    keycode.KC_F4: "F4",
    keycode.KC_F5: "F5",
    keycode.KC_F6: "F6",
    keycode.KC_F7: "F7",
    keycode.KC_F8: "F8",
    keycode.KC_F9: "F9",
    keycode.KC_F10: "F10",
    keycode.KC_F11: "F11",
    keycode.KC_F12: "F12",
    keycode.KC_PRINT_SCREEN: "PrintScreen",
    keycode.KC_SCROLL_LOCK: "ScrollLock",
    keycode.KC_PAUSE: "Pause",
    keycode.KC_INSERT: "Insert",
    keycode.KC_HOME: "Home",
    keycode.KC_PAGE_UP: "PageUp",
    keycode.KC_DELETE: "Delete",
    keycode.KC_END: "End",
    keycode.KC_PAGE_DOWN: "PageDown",
    keycode.KC_RIGHT: "Right",
    keycode.KC_LEFT: "Left",
    keycode.KC_DOWN: "Down",
    keycode.KC_UP: "Up",
    keycode.KC_NUM_LOCK: "NumLock",
    keycode.KC_KP_SLASH: "KPSlash",
    keycode.KC_KP_ASTERISK: "KPAsterisk",
    keycode.KC_KP_MINUS: "KPMinus",
    keycode.KC_KP_PLUS: "KPPlus",
    keycode.KC_KP_ENTER: "KPEnter",
    keycode.KC_KP_1: "KP1",
    keycode.KC_KP_2: "KP2",
    keycode.KC_KP_3: "KP3",
    keycode.KC_KP_4: "KP4",
    keycode.KC_KP_5: "KP5",
    keycode.KC_KP_6: "KP6",
    keycode.KC_KP_7: "KP7",
    keycode.KC_KP_8: "KP8",
    keycode.KC_KP_9: "KP9",
    keycode.KC_KP_0: "KP0",
    keycode.KC_KP_DOT: "KPPeriod",
    keycode.KC_NONUS_BACKSLASH: "KC_NONUS_BACKSLASH",
    keycode.KC_APPLICATION: "Application",
    keycode.KC_KB_POWER: "KC_KB_POWER",
    keycode.KC_KP_EQUAL: "KPEqual",
    keycode.KC_F13: "F13",
    keycode.KC_F14: "F14",
    keycode.KC_F15: "F15",
    keycode.KC_F16: "F16",
    keycode.KC_F17: "F17",
    keycode.KC_F18: "F18",
    keycode.KC_F19: "F19",
    keycode.KC_F20: "F20",
    keycode.KC_F21: "F21",
    keycode.KC_F22: "F22",
    keycode.KC_F23: "F23",
    keycode.KC_F24: "F24",
    keycode.KC_EXECUTE: "KC_EXECUTE",
    keycode.KC_HELP: "KC_HELP",
    keycode.KC_MENU: "Menu",
    keycode.KC_SELECT: "KC_SELECT",
    keycode.KC_STOP: "KC_STOP",
    keycode.KC_AGAIN: "KC_AGAIN",
    keycode.KC_UNDO: "KC_UNDO",
    keycode.KC_CUT: "KC_CUT",
    keycode.KC_COPY: "KC_COPY",
    keycode.KC_PASTE: "KC_PASTE",
    keycode.KC_FIND: "KC_FIND",
    keycode.KC_KB_MUTE: "KC_KB_MUTE",
    keycode.KC_KB_VOLUME_UP: "KC_KB_VOLUME_UP",
    keycode.KC_KB_VOLUME_DOWN: "KC_KB_VOLUME_DOWN",
    keycode.KC_LOCKING_CAPS_LOCK: "KC_LOCKING_CAPS_LOCK",
    keycode.KC_LOCKING_NUM_LOCK: "KC_LOCKING_NUM_LOCK",
    keycode.KC_LOCKING_SCROLL_LOCK: "KC_LOCKING_SCROLL_LOCK",
    keycode.KC_KP_COMMA: "KC_KP_COMMA",
    keycode.KC_KP_EQUAL_AS400: "KC_KP_EQUAL_AS400",
    keycode.KC_INTERNATIONAL_1: "KC_INTERNATIONAL_1",
    keycode.KC_INTERNATIONAL_2: "KC_INTERNATIONAL_2",
    keycode.KC_INTERNATIONAL_3: "KC_INTERNATIONAL_3",
    keycode.KC_INTERNATIONAL_4: "KC_INTERNATIONAL_4",
    keycode.KC_INTERNATIONAL_5: "KC_INTERNATIONAL_5",
    keycode.KC_INTERNATIONAL_6: "KC_INTERNATIONAL_6",
    keycode.KC_INTERNATIONAL_7: "KC_INTERNATIONAL_7",
    keycode.KC_INTERNATIONAL_8: "KC_INTERNATIONAL_8",
    keycode.KC_INTERNATIONAL_9: "KC_INTERNATIONAL_9",
    keycode.KC_LANGUAGE_1: "KC_LANGUAGE_1",
    keycode.KC_LANGUAGE_2: "KC_LANGUAGE_2",
    keycode.KC_LANGUAGE_3: "KC_LANGUAGE_3",
    keycode.KC_LANGUAGE_4: "KC_LANGUAGE_4",
    keycode.KC_LANGUAGE_5: "KC_LANGUAGE_5",
    keycode.KC_LANGUAGE_6: "KC_LANGUAGE_6",
    keycode.KC_LANGUAGE_7: "KC_LANGUAGE_7",
    keycode.KC_LANGUAGE_8: "KC_LANGUAGE_8",
    keycode.KC_LANGUAGE_9: "KC_LANGUAGE_9",
    keycode.KC_ALTERNATE_ERASE: "KC_ALTERNATE_ERASE",
    keycode.KC_SYSTEM_REQUEST: "KC_SYSTEM_REQUEST",
    keycode.KC_CANCEL: "KC_CANCEL",
    keycode.KC_CLEAR: "KC_CLEAR",
    keycode.KC_PRIOR: "KC_PRIOR",
    keycode.KC_RETURN: "KC_RETURN",
    keycode.KC_SEPARATOR: "KC_SEPARATOR",
    keycode.KC_OUT: "KC_OUT",
    keycode.KC_OPER: "KC_OPER",
    keycode.KC_CLEAR_AGAIN: "KC_CLEAR_AGAIN",
    keycode.KC_CRSEL: "KC_CRSEL",
    keycode.KC_EXSEL: "KC_EXSEL",
    keycode.KC_SYSTEM_POWER: "KC_SYSTEM_POWER",
    keycode.KC_SYSTEM_SLEEP: "KC_SYSTEM_SLEEP",
    keycode.KC_SYSTEM_WAKE: "KC_SYSTEM_WAKE",
    keycode.KC_AUDIO_MUTE: "Mute",
    keycode.KC_AUDIO_VOL_UP: "VolumeUp",
    keycode.KC_AUDIO_VOL_DOWN: "VolumeDown",
    keycode.KC_MEDIA_NEXT_TRACK: "NextTrack",
    keycode.KC_MEDIA_PREV_TRACK: "PrevTrack",
    keycode.KC_MEDIA_STOP: "Stop",
    keycode.KC_MEDIA_PLAY_PAUSE: "PlayPause",
    keycode.KC_MEDIA_SELECT: "KC_MEDIA_SELECT",
    keycode.KC_MEDIA_EJECT: "KC_MEDIA_EJECT",
    keycode.KC_MAIL: "KC_MAIL",
    keycode.KC_CALCULATOR: "Calculator",
    keycode.KC_MY_COMPUTER: "KC_MY_COMPUTER",
    keycode.KC_WWW_SEARCH: "KC_WWW_SEARCH",
    keycode.KC_WWW_HOME: "KC_WWW_HOME",
    keycode.KC_WWW_BACK: "KC_WWW_BACK",
    keycode.KC_WWW_FORWARD: "KC_WWW_FORWARD",
    keycode.KC_WWW_STOP: "KC_WWW_STOP",
    keycode.KC_WWW_REFRESH: "KC_WWW_REFRESH",
    keycode.KC_WWW_FAVORITES: "KC_WWW_FAVORITES",
    keycode.KC_MEDIA_FAST_FORWARD: "KC_MEDIA_FAST_FORWARD",
    keycode.KC_MEDIA_REWIND: "KC_MEDIA_REWIND",
    keycode.KC_BRIGHTNESS_UP: "BrightUp",
    keycode.KC_BRIGHTNESS_DOWN: "BrightDown",
    keycode.KC_CONTROL_PANEL: "KC_CONTROL_PANEL",
    keycode.KC_ASSISTANT: "KC_ASSISTANT",
    keycode.KC_MISSION_CONTROL: "KC_MISSION_CONTROL",
    keycode.KC_LAUNCHPAD: "KC_LAUNCHPAD",
    keycode.QK_MOUSE_CURSOR_UP: "QK_MOUSE_CURSOR_UP",
    keycode.QK_MOUSE_CURSOR_DOWN: "QK_MOUSE_CURSOR_DOWN",
    keycode.QK_MOUSE_CURSOR_LEFT: "QK_MOUSE_CURSOR_LEFT",
    keycode.QK_MOUSE_CURSOR_RIGHT: "QK_MOUSE_CURSOR_RIGHT",
    keycode.QK_MOUSE_BUTTON_1: "QK_MOUSE_BUTTON_1",
    keycode.QK_MOUSE_BUTTON_2: "QK_MOUSE_BUTTON_2",
    keycode.QK_MOUSE_BUTTON_3: "QK_MOUSE_BUTTON_3",
    keycode.QK_MOUSE_BUTTON_4: "QK_MOUSE_BUTTON_4",
    keycode.QK_MOUSE_BUTTON_5: "QK_MOUSE_BUTTON_5",
    keycode.QK_MOUSE_BUTTON_6: "QK_MOUSE_BUTTON_6",
    keycode.QK_MOUSE_BUTTON_7: "QK_MOUSE_BUTTON_7",
    keycode.QK_MOUSE_BUTTON_8: "QK_MOUSE_BUTTON_8",
    keycode.QK_MOUSE_WHEEL_UP: "QK_MOUSE_WHEEL_UP",
    keycode.QK_MOUSE_WHEEL_DOWN: "QK_MOUSE_WHEEL_DOWN",
    keycode.QK_MOUSE_WHEEL_LEFT: "QK_MOUSE_WHEEL_LEFT",
    keycode.QK_MOUSE_WHEEL_RIGHT: "QK_MOUSE_WHEEL_RIGHT",
    keycode.QK_MOUSE_ACCELERATION_0: "QK_MOUSE_ACCELERATION_0",
    keycode.QK_MOUSE_ACCELERATION_1: "QK_MOUSE_ACCELERATION_1",
    keycode.QK_MOUSE_ACCELERATION_2: "QK_MOUSE_ACCELERATION_2",
    keycode.KC_LEFT_CTRL: "Ctrl",
    keycode.KC_LEFT_SHIFT: "Shift",
    keycode.KC_LEFT_ALT: "Alt",
    keycode.KC_LEFT_GUI: "Win",
    keycode.KC_RIGHT_CTRL: "RCtrl",
    keycode.KC_RIGHT_SHIFT: "RShift",
    keycode.KC_RIGHT_ALT: "RAlt",
    keycode.KC_RIGHT_GUI: "RWin",


    (keycode.KC_LEFT_SHIFT, keycode.KC_A): "A",
    (keycode.KC_LEFT_SHIFT, keycode.KC_B): "B",
    (keycode.KC_LEFT_SHIFT, keycode.KC_C): "C",
    (keycode.KC_LEFT_SHIFT, keycode.KC_D): "D",
    (keycode.KC_LEFT_SHIFT, keycode.KC_E): "E",
    (keycode.KC_LEFT_SHIFT, keycode.KC_F): "F",
    (keycode.KC_LEFT_SHIFT, keycode.KC_G): "G",
    (keycode.KC_LEFT_SHIFT, keycode.KC_H): "H",
    (keycode.KC_LEFT_SHIFT, keycode.KC_I): "I",
    (keycode.KC_LEFT_SHIFT, keycode.KC_J): "J",
    (keycode.KC_LEFT_SHIFT, keycode.KC_K): "K",
    (keycode.KC_LEFT_SHIFT, keycode.KC_L): "L",
    (keycode.KC_LEFT_SHIFT, keycode.KC_M): "M",
    (keycode.KC_LEFT_SHIFT, keycode.KC_N): "N",
    (keycode.KC_LEFT_SHIFT, keycode.KC_O): "O",
    (keycode.KC_LEFT_SHIFT, keycode.KC_P): "P",
    (keycode.KC_LEFT_SHIFT, keycode.KC_Q): "Q",
    (keycode.KC_LEFT_SHIFT, keycode.KC_R): "R",
    (keycode.KC_LEFT_SHIFT, keycode.KC_S): "S",
    (keycode.KC_LEFT_SHIFT, keycode.KC_T): "T",
    (keycode.KC_LEFT_SHIFT, keycode.KC_U): "U",
    (keycode.KC_LEFT_SHIFT, keycode.KC_V): "V",
    (keycode.KC_LEFT_SHIFT, keycode.KC_W): "W",
    (keycode.KC_LEFT_SHIFT, keycode.KC_X): "X",
    (keycode.KC_LEFT_SHIFT, keycode.KC_Y): "Y",
    (keycode.KC_LEFT_SHIFT, keycode.KC_Z): "Z",

    (keycode.KC_LEFT_SHIFT, keycode.KC_GRAVE): "~",
    (keycode.KC_LEFT_SHIFT, keycode.KC_1): "!",
    (keycode.KC_LEFT_SHIFT, keycode.KC_2): "@",
    (keycode.KC_LEFT_SHIFT, keycode.KC_3): "#",
    (keycode.KC_LEFT_SHIFT, keycode.KC_4): "$",
    (keycode.KC_LEFT_SHIFT, keycode.KC_5): "%",
    (keycode.KC_LEFT_SHIFT, keycode.KC_6): "^",
    (keycode.KC_LEFT_SHIFT, keycode.KC_7): "&",
    (keycode.KC_LEFT_SHIFT, keycode.KC_8): "*",
    (keycode.KC_LEFT_SHIFT, keycode.KC_9): "(",
    (keycode.KC_LEFT_SHIFT, keycode.KC_0): ")",
    (keycode.KC_LEFT_SHIFT, keycode.KC_MINUS): "_",
    (keycode.KC_LEFT_SHIFT, keycode.KC_EQUAL): "+",
    (keycode.KC_LEFT_SHIFT, keycode.KC_LEFT_BRACKET): "{",
    (keycode.KC_LEFT_SHIFT, keycode.KC_RIGHT_BRACKET): "}",
    (keycode.KC_LEFT_SHIFT, keycode.KC_BACKSLASH): "|",
    (keycode.KC_LEFT_SHIFT, keycode.KC_SEMICOLON): ":",
    (keycode.KC_LEFT_SHIFT, keycode.KC_QUOTE): "\"",
    (keycode.KC_LEFT_SHIFT, keycode.KC_COMMA): "<",
    (keycode.KC_LEFT_SHIFT, keycode.KC_DOT): ">",
    (keycode.KC_LEFT_SHIFT, keycode.KC_SLASH): "?",

}
