# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(527, 345)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(12)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_Minus = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Minus.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButton_Minus.setStyleSheet("\n"
"          QPushButton {\n"
"            border-radius: 5px;\n"
"            background-color: #eee;\n"
"            padding: 5px;\n"
"            font-weight: 500;\n"
"          }\n"
"          QPushButton:hover {\n"
"            background-color: #ddd;\n"
"          }\n"
"         ")
        self.pushButton_Minus.setFlat(True)
        self.pushButton_Minus.setObjectName("pushButton_Minus")
        self.horizontalLayout_2.addWidget(self.pushButton_Minus)
        self.pushButton_Plus = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Plus.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButton_Plus.setStyleSheet("\n"
"          QPushButton {\n"
"            border-radius: 5px;\n"
"            background-color: #eee;\n"
"            padding: 5px;\n"
"            font-weight: 500;\n"
"          }\n"
"          QPushButton:hover {\n"
"            background-color: #ddd;\n"
"          }\n"
"         ")
        self.pushButton_Plus.setFlat(True)
        self.pushButton_Plus.setObjectName("pushButton_Plus")
        self.horizontalLayout_2.addWidget(self.pushButton_Plus)
        self.label_keysPerSecond = QtWidgets.QLabel(self.centralwidget)
        self.label_keysPerSecond.setMaximumSize(QtCore.QSize(16777215, 16))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_keysPerSecond.setFont(font)
        self.label_keysPerSecond.setStyleSheet("color: #444; background: transparent;")
        self.label_keysPerSecond.setAlignment(QtCore.Qt.AlignCenter)
        self.label_keysPerSecond.setObjectName("label_keysPerSecond")
        self.horizontalLayout_2.addWidget(self.label_keysPerSecond)
        self.label_line = QtWidgets.QLabel(self.centralwidget)
        self.label_line.setMaximumSize(QtCore.QSize(135, 16777214))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_line.setFont(font)
        self.label_line.setStyleSheet("color: #444; background: transparent;")
        self.label_line.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_line.setObjectName("label_line")
        self.horizontalLayout_2.addWidget(self.label_line)
        self.pushButton_Back = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Back.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButton_Back.setStyleSheet("\n"
"          QPushButton {\n"
"            border-radius: 5px;\n"
"            background-color: #eee;\n"
"            padding: 5px;\n"
"            font-weight: 500;\n"
"          }\n"
"          QPushButton:hover {\n"
"            background-color: #ddd;\n"
"          }\n"
"         ")
        self.pushButton_Back.setFlat(True)
        self.pushButton_Back.setObjectName("pushButton_Back")
        self.horizontalLayout_2.addWidget(self.pushButton_Back)
        self.pushButton_Next = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Next.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButton_Next.setStyleSheet("\n"
"          QPushButton {\n"
"            border-radius: 5px;\n"
"            background-color: #eee;\n"
"            padding: 5px;\n"
"            font-weight: 500;\n"
"          }\n"
"          QPushButton:hover {\n"
"            background-color: #ddd;\n"
"          }\n"
"         ")
        self.pushButton_Next.setFlat(True)
        self.pushButton_Next.setObjectName("pushButton_Next")
        self.horizontalLayout_2.addWidget(self.pushButton_Next)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(8)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_keysPressed = QtWidgets.QLabel(self.centralwidget)
        self.label_keysPressed.setStyleSheet("\n"
"          background-color: #f9fbff;\n"
"          border: 1px solid #ccc;\n"
"          border-radius: 8px;\n"
"          padding: 6px;\n"
"          color: #222;\n"
"         ")
        self.label_keysPressed.setAlignment(QtCore.Qt.AlignCenter)
        self.label_keysPressed.setObjectName("label_keysPressed")
        self.horizontalLayout.addWidget(self.label_keysPressed)
        self.lineEdit = VisibleWhitespaceTextEdit(self.centralwidget)
        self.lineEdit.setStyleSheet("\n"
"          QPlainTextEdit {\n"
"            background-color: #f9fbff;\n"
"            border: 1px solid #ccc;\n"
"            border-radius: 8px;\n"
"            padding: 8px;\n"
"            color: #222;\n"
"            font-weight: normal;\n"
"            padding: 0.5px;\n"
"            text-align: left;\n"
"          }\n"
"         ")
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.textedit_keyPrompt = VisibleWhitespaceTextEdit(self.centralwidget)
        self.textedit_keyPrompt.setStyleSheet("\n"
"        QPlainTextEdit {\n"
"          background-color: #f9fbff;\n"
"          border: 1px solid #ccc;\n"
"          border-radius: 8px;\n"
"          padding: 8px;\n"
"          color: #222;\n"
"          padding: 0.5px;\n"
"          text-align: left;\n"
"        }\n"
"\n"
"        /* Vertical scrollbar */\n"
"        QScrollBar:vertical {\n"
"          border: none;\n"
"          background: #f0f2f5;\n"
"          width: 12px;\n"
"          margin: 2px 0 2px 0;\n"
"          border-radius: 6px;\n"
"        }\n"
"        QScrollBar::handle:vertical {\n"
"          background: #bbb;\n"
"          min-height: 20px;\n"
"          border-radius: 6px;\n"
"        }\n"
"        QScrollBar::handle:vertical:hover {\n"
"          background: #999;\n"
"        }\n"
"        QScrollBar::add-line:vertical,\n"
"        QScrollBar::sub-line:vertical {\n"
"          border: none;\n"
"          background: none;\n"
"          height: 0;\n"
"        }\n"
"\n"
"        /* Horizontal scrollbar */\n"
"        QScrollBar:horizontal {\n"
"          border: none;\n"
"          background: #f0f2f5;\n"
"          height: 12px;\n"
"          margin: 0 2px 0 2px;\n"
"          border-radius: 6px;\n"
"        }\n"
"        QScrollBar::handle:horizontal {\n"
"          background: #bbb;\n"
"          min-width: 20px;\n"
"          border-radius: 6px;\n"
"        }\n"
"        QScrollBar::handle:horizontal:hover {\n"
"          background: #999;\n"
"        }\n"
"        QScrollBar::add-line:horizontal,\n"
"        QScrollBar::sub-line:horizontal {\n"
"          border: none;\n"
"          background: none;\n"
"          width: 0;\n"
"        }\n"
"      ")
        self.textedit_keyPrompt.setReadOnly(True)
        self.textedit_keyPrompt.setObjectName("textedit_keyPrompt")
        self.verticalLayout.addWidget(self.textedit_keyPrompt)
        self.label_keyPrompt = QtWidgets.QLabel(self.centralwidget)
        self.label_keyPrompt.setStyleSheet("\n"
"        background-color: #f9fbff;\n"
"        border: 1px solid #ccc;\n"
"        border-radius: 8px;\n"
"        padding: 8px;\n"
"        color: #222;\n"
"      ")
        self.label_keyPrompt.setAlignment(QtCore.Qt.AlignCenter)
        self.label_keyPrompt.setWordWrap(True)
        self.label_keyPrompt.setObjectName("label_keyPrompt")
        self.verticalLayout.addWidget(self.label_keyPrompt)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 527, 35))
        self.menubar.setStyleSheet("\n"
"        QMenuBar {\n"
"            background-color: #f4f4f4;\n"
"            spacing: 6px;\n"
"            padding: 2px;\n"
"            color: black; /* normal text color */\n"
"        }\n"
"        QMenuBar::item {\n"
"            spacing: 4px;\n"
"            padding: 5px 12px;\n"
"            background: transparent;\n"
"            font-weight: 500;\n"
"            color: black; /* force text visible */\n"
"        }\n"
"        QMenuBar::item:hover {\n"
"            background-color: #ddd;\n"
"            border-radius: 4px;\n"
"            color: black; /* ensure text visible */\n"
"        }\n"
"        QMenuBar::item:pressed {\n"
"            background-color: #ccc;\n"
"            border-radius: 4px;\n"
"            color: black;\n"
"        }\n"
"        QMenu {\n"
"            background-color: #f9f9f9;\n"
"            border: 1px solid #ccc;\n"
"            padding: 6px;\n"
"            color: black; /* menu item text color */\n"
"        }\n"
"        QMenu::item:selected {\n"
"            background-color: #ddd;\n"
"            border-radius: 4px;\n"
"            color: black;\n"
"        }\n"
"    ")
        self.menubar.setObjectName("menubar")
        self.menuMode = QtWidgets.QMenu(self.menubar)
        self.menuMode.setObjectName("menuMode")
        self.menuOptions = QtWidgets.QMenu(self.menubar)
        self.menuOptions.setObjectName("menuOptions")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionKey_Practice = QtWidgets.QAction(MainWindow)
        self.actionKey_Practice.setCheckable(True)
        self.actionKey_Practice.setChecked(True)
        self.actionKey_Practice.setObjectName("actionKey_Practice")
        self.actionTyping_Practice = QtWidgets.QAction(MainWindow)
        self.actionTyping_Practice.setCheckable(True)
        self.actionTyping_Practice.setObjectName("actionTyping_Practice")
        self.actionLoad_typing_content_file = QtWidgets.QAction(MainWindow)
        self.actionLoad_typing_content_file.setObjectName("actionLoad_typing_content_file")
        self.actionNumbers = QtWidgets.QAction(MainWindow)
        self.actionNumbers.setCheckable(True)
        self.actionNumbers.setChecked(True)
        self.actionNumbers.setObjectName("actionNumbers")
        self.actionSymbols = QtWidgets.QAction(MainWindow)
        self.actionSymbols.setCheckable(True)
        self.actionSymbols.setChecked(True)
        self.actionSymbols.setObjectName("actionSymbols")
        self.actionSpecials = QtWidgets.QAction(MainWindow)
        self.actionSpecials.setCheckable(True)
        self.actionSpecials.setChecked(True)
        self.actionSpecials.setObjectName("actionSpecials")
        self.actionLowercase = QtWidgets.QAction(MainWindow)
        self.actionLowercase.setCheckable(True)
        self.actionLowercase.setChecked(True)
        self.actionLowercase.setObjectName("actionLowercase")
        self.actionUppercase = QtWidgets.QAction(MainWindow)
        self.actionUppercase.setCheckable(True)
        self.actionUppercase.setChecked(True)
        self.actionUppercase.setObjectName("actionUppercase")
        self.actionModifiers = QtWidgets.QAction(MainWindow)
        self.actionModifiers.setCheckable(True)
        self.actionModifiers.setChecked(True)
        self.actionModifiers.setObjectName("actionModifiers")
        self.actionFunction = QtWidgets.QAction(MainWindow)
        self.actionFunction.setCheckable(True)
        self.actionFunction.setChecked(True)
        self.actionFunction.setObjectName("actionFunction")
        self.actionCombos = QtWidgets.QAction(MainWindow)
        self.actionCombos.setCheckable(True)
        self.actionCombos.setChecked(True)
        self.actionCombos.setObjectName("actionCombos")
        self.actionWords_Top_10 = QtWidgets.QAction(MainWindow)
        self.actionWords_Top_10.setCheckable(True)
        self.actionWords_Top_10.setObjectName("actionWords_Top_10")
        self.actionWords_Top_100 = QtWidgets.QAction(MainWindow)
        self.actionWords_Top_100.setCheckable(True)
        self.actionWords_Top_100.setObjectName("actionWords_Top_100")
        self.actionWords_Top_1000 = QtWidgets.QAction(MainWindow)
        self.actionWords_Top_1000.setCheckable(True)
        self.actionWords_Top_1000.setObjectName("actionWords_Top_1000")
        self.actionWords_All = QtWidgets.QAction(MainWindow)
        self.actionWords_All.setCheckable(True)
        self.actionWords_All.setObjectName("actionWords_All")
        self.actionSerif_Font = QtWidgets.QAction(MainWindow)
        self.actionSerif_Font.setCheckable(True)
        self.actionSerif_Font.setChecked(True)
        self.actionSerif_Font.setObjectName("actionSerif_Font")
        self.actionAdvance_On_Enter = QtWidgets.QAction(MainWindow)
        self.actionAdvance_On_Enter.setCheckable(True)
        self.actionAdvance_On_Enter.setObjectName("actionAdvance_On_Enter")
        self.actionAdvance_On_Space = QtWidgets.QAction(MainWindow)
        self.actionAdvance_On_Space.setCheckable(True)
        self.actionAdvance_On_Space.setObjectName("actionAdvance_On_Space")
        self.menuMode.addAction(self.actionKey_Practice)
        self.menuMode.addAction(self.actionTyping_Practice)
        self.menuMode.addAction(self.actionWords_Top_10)
        self.menuMode.addAction(self.actionWords_Top_100)
        self.menuMode.addAction(self.actionWords_Top_1000)
        self.menuMode.addAction(self.actionWords_All)
        self.menuOptions.addAction(self.actionSerif_Font)
        self.menuOptions.addAction(self.actionAdvance_On_Enter)
        self.menuOptions.addAction(self.actionAdvance_On_Space)
        self.menuOptions.addAction(self.actionNumbers)
        self.menuOptions.addAction(self.actionSymbols)
        self.menuOptions.addAction(self.actionSpecials)
        self.menuOptions.addAction(self.actionModifiers)
        self.menuOptions.addAction(self.actionLowercase)
        self.menuOptions.addAction(self.actionUppercase)
        self.menuOptions.addAction(self.actionFunction)
        self.menuOptions.addAction(self.actionCombos)
        self.menuFile.addAction(self.actionLoad_typing_content_file)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuMode.menuAction())
        self.menubar.addAction(self.menuOptions.menuAction())

        self.retranslateUi(MainWindow)
        self.actionKey_Practice.toggled['bool'].connect(MainWindow.actionModeKey) # type: ignore
        self.actionTyping_Practice.toggled['bool'].connect(MainWindow.actionModeTyping) # type: ignore
        self.lineEdit.textChanged.connect(MainWindow.lineEditTextChanged) # type: ignore
        self.actionLoad_typing_content_file.triggered.connect(MainWindow.loadTypingPromptFile) # type: ignore
        self.actionCombos.toggled['bool'].connect(MainWindow.keyTypeToggled) # type: ignore
        self.actionFunction.toggled['bool'].connect(MainWindow.keyTypeToggled) # type: ignore
        self.actionLowercase.toggled['bool'].connect(MainWindow.keyTypeToggled) # type: ignore
        self.actionModifiers.toggled['bool'].connect(MainWindow.keyTypeToggled) # type: ignore
        self.actionNumbers.toggled['bool'].connect(MainWindow.keyTypeToggled) # type: ignore
        self.actionSpecials.toggled['bool'].connect(MainWindow.keyTypeToggled) # type: ignore
        self.actionSymbols.toggled['bool'].connect(MainWindow.keyTypeToggled) # type: ignore
        self.actionUppercase.toggled['bool'].connect(MainWindow.keyTypeToggled) # type: ignore
        self.actionWords_Top_10.toggled['bool'].connect(MainWindow.actionModeTyping) # type: ignore
        self.actionWords_Top_100.toggled['bool'].connect(MainWindow.actionModeTyping) # type: ignore
        self.actionWords_Top_1000.toggled['bool'].connect(MainWindow.actionModeTyping) # type: ignore
        self.actionWords_All.toggled['bool'].connect(MainWindow.actionModeTyping) # type: ignore
        self.pushButton_Next.clicked.connect(MainWindow.nextButton) # type: ignore
        self.pushButton_Back.clicked.connect(MainWindow.backButton) # type: ignore
        self.actionSerif_Font.toggled['bool'].connect(MainWindow.actionSerifFont) # type: ignore
        self.pushButton_Plus.clicked.connect(MainWindow.plusButton) # type: ignore
        self.pushButton_Minus.clicked.connect(MainWindow.minusButton) # type: ignore
        self.actionAdvance_On_Enter.toggled['bool'].connect(MainWindow.actionAdvanceOnEnter) # type: ignore
        self.actionAdvance_On_Space.toggled['bool'].connect(MainWindow.actionAdvanceOnSpace) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Mapping Trainer"))
        self.pushButton_Minus.setText(_translate("MainWindow", "-"))
        self.pushButton_Plus.setText(_translate("MainWindow", "+"))
        self.label_keysPerSecond.setText(_translate("MainWindow", "--"))
        self.label_line.setText(_translate("MainWindow", "99999 / 99999"))
        self.pushButton_Back.setText(_translate("MainWindow", "<"))
        self.pushButton_Next.setText(_translate("MainWindow", ">"))
        self.label_keyPrompt.setText(_translate("MainWindow", "KEY TO TYPE"))
        self.menuMode.setTitle(_translate("MainWindow", "Mode"))
        self.menuOptions.setTitle(_translate("MainWindow", "Options"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionKey_Practice.setText(_translate("MainWindow", "Keys"))
        self.actionTyping_Practice.setText(_translate("MainWindow", "Typing"))
        self.actionLoad_typing_content_file.setText(_translate("MainWindow", "Load typing content file..."))
        self.actionNumbers.setText(_translate("MainWindow", "Numbers"))
        self.actionSymbols.setText(_translate("MainWindow", "Symbols"))
        self.actionSpecials.setText(_translate("MainWindow", "Specials"))
        self.actionLowercase.setText(_translate("MainWindow", "Lowercase"))
        self.actionUppercase.setText(_translate("MainWindow", "Uppercase"))
        self.actionModifiers.setText(_translate("MainWindow", "Modifiers"))
        self.actionFunction.setText(_translate("MainWindow", "Function"))
        self.actionCombos.setText(_translate("MainWindow", "Combos"))
        self.actionWords_Top_10.setText(_translate("MainWindow", "Words (Top 10)"))
        self.actionWords_Top_100.setText(_translate("MainWindow", "Words (Top 100)"))
        self.actionWords_Top_1000.setText(_translate("MainWindow", "Words (Top 1000)"))
        self.actionWords_All.setText(_translate("MainWindow", "Words (All)"))
        self.actionSerif_Font.setText(_translate("MainWindow", "Serif Font"))
        self.actionAdvance_On_Enter.setText(_translate("MainWindow", "Advance On Enter"))
        self.actionAdvance_On_Space.setText(_translate("MainWindow", "Advance On Space"))
from visibleWhitespaceTextEdit import VisibleWhitespaceTextEdit
