# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(403, 208)
        self.verticalLayout = QtWidgets.QVBoxLayout(mainWindow)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_keysPressed = QtWidgets.QLabel(mainWindow)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_keysPressed.setFont(font)
        self.label_keysPressed.setAlignment(QtCore.Qt.AlignCenter)
        self.label_keysPressed.setObjectName("label_keysPressed")
        self.verticalLayout.addWidget(self.label_keysPressed)
        self.label_keyPrompt = QtWidgets.QLabel(mainWindow)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_keyPrompt.setFont(font)
        self.label_keyPrompt.setAlignment(QtCore.Qt.AlignCenter)
        self.label_keyPrompt.setObjectName("label_keyPrompt")
        self.verticalLayout.addWidget(self.label_keyPrompt)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "Mapping Trainer"))
        self.label_keysPressed.setText(_translate("mainWindow", "KEYS PRESSED"))
        self.label_keyPrompt.setText(_translate("mainWindow", "KEY TO TYPE"))
