# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(491, 387)
        self.label_keyPrompt = QtWidgets.QLabel(Form)
        self.label_keyPrompt.setGeometry(QtCore.QRect(90, 290, 281, 81))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_keyPrompt.setFont(font)
        self.label_keyPrompt.setAlignment(QtCore.Qt.AlignCenter)
        self.label_keyPrompt.setObjectName("label_keyPrompt")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_keyPrompt.setText(_translate("Form", "KEY TO TYPE"))
